from . import instructors
from . import salary
from . import gpt
from . import check_list
from . import cash_report
from . import new_employee
from . import analitic
from . import change_employee
from . import swap
